<?php

namespace App\Models;

class ProBom extends Model
{
    protected $table = 'pro_bom';

    protected $fillable = [
        'commodity_code', 'spec_code', 'short_name', 'spec',
        'color', 'material_quality', 'special', 'other', 'status',
    ];

    //设置类型
    protected $casts = [
        'status' => 'boolean',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($model) {
            $model->proBomMaterial()->delete();
        });
    }

    public function proBomMaterial()
    {
        return $this->hasMany(ProBomMaterial::class);
    }
}
