<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class RefundOrder extends Model
{
    protected $table = 'refund_orders';

    const REFUND_STATUS_NEW = 10;
    const REFUND_STATUS_LOCK = 15;
    const REFUND_STATUS_CS_AUDIT = 30;
    const REFUND_STATUS_AS_LOCK = 35;
    const REFUND_STATUS_AS_AUDIT = 40;
    const REFUND_STATUS_FD_LOCK = 45;
    const REFUND_STATUS_FD_AUDIT = 50;

    //订单来源
    const ORDER_SOURCE_SYSTEM = 'system';
    const ORDER_SOURCE_TAOBAO = 'taobao';

    //订单状态
    public static $refundStatusMap = [
        self::REFUND_STATUS_NEW => '未处理',
        self::REFUND_STATUS_LOCK => '订单锁定',
        self::REFUND_STATUS_CS_AUDIT => '已客审',
        self::REFUND_STATUS_AS_LOCK => '售后锁定',
        self::REFUND_STATUS_AS_AUDIT => '已后审',
        self::REFUND_STATUS_FD_LOCK => '财务锁定',
        self::REFUND_STATUS_FD_AUDIT => '已财审',
    ];

    protected $fillable = [
        'id',
        'refund_sn',
        'order_sn',
        'order_no',
        'shops_id',
        'refund_order_status',
        'order_source',
        'payment_amount',
        'refund_amount',
        'refund_payment_methods_id',
        'refund_account',
        'bank',
        'bank_address',
        'refund_reason_type_id',
        'refund_reason',
        'buyer_nick',
        'buyer_name',
        'order_time',
        'order_price',
        'is_delivered',
        'receipt_type',
        'transaction_sn',
        'paipai_sn',
        'responsible_party',
        'responsible_person',
        'responsible_amount',
        'freight_fee',
        'business_remark',
        'as_remark',
        'f_remark',
        'refund_description',
        'taobao_refund_status',
        'creator_id',
        'business_personnel_id',
        'locker_id',
        'after_sales_id',
        'financial_id',
        'locked_at',
        'cs_audit_at',
        'as_audit_at',
        'f_audit_at',
        'status',
        'created_at',
        'updated_at',
    ];

    //设置类型
    protected $casts = [
        'is_delivered' => 'boolean',
        'status' => 'boolean',
    ];

    protected $dates = [
        'locked_at',
        'cs_audit_at',
        'as_audit_at',
        'f_audit_at',
        'created_at',
        'updated_at',
    ];

    //观察者
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // 监听模型创建事件，在写入数据库之前触发
        static::creating(function ($model) {
            // 如果模型的 refund_sn 字段为空
            if (!$model->refund_sn) {
                // 调用 findAvailableNo 生成订单流水号
                $model->refund_sn = static::findAvailableNo('RA', 'refund_sn');
                // 如果生成失败，则终止创建订单
                if (!$model->refund_sn) {
                    return false;
                }
            }

            // 如果模型的 order_source 字段为空
            if (!$model->order_source) {
                $model->order_source = self::ORDER_SOURCE_SYSTEM;
                // 如果生成失败，则终止创建订单
                if (!$model->order_source) {
                    return false;
                }
            }

            // 如果模型的 refund_order_status 字段为空
            if (!$model->refund_order_status) {
                $model->refund_order_status = self::REFUND_STATUS_NEW;
                // 如果生成失败，则终止创建订单
                if (!$model->refund_order_status) {
                    return false;
                }
            }

            // 如果模型的 creator_id 字段为空
            if (!$model->creator_id) {
                $model->creator_id = Auth::guard('api')->id();
                // 如果生成失败，则终止创建订单
                if (!$model->creator_id) {
                    return false;
                }
            }
        });
    }

    /**
     * 订单未锁定.
     *
     * @return bool
     */
    public function unlock()
    {
        return !(($this->getOriginal('refund_order_status') == self::REFUND_STATUS_LOCK) || ($this->getOriginal('refund_order_status') == self::REFUND_STATUS_AS_LOCK) || ($this->getOriginal('refund_order_status') == self::REFUND_STATUS_FD_LOCK));
    }

    /**
     * 订单锁定或释放.
     *
     * @return bool
     */
    public function lockOrUnlock()
    {
        if ($this->unlock()) {
            $this->business_personnel_id = Auth::guard('api')->id();
            $this->locker_id = Auth::guard('api')->id();
            $this->refund_order_status = self::REFUND_STATUS_LOCK;

            $userId = Auth::guard('api')->id();
            $userName = User::find($userId)->real_name;
            $operationData = new RefundOperationRecord;
            $operationData->refund_orders_id = $this->id;
            $operationData->user_id = Auth::guard('api')->id();
            $operationData->user_name = $userName;
            $operationData->operation = "锁定";
            $operationData->description = "订单锁定";
            $operationData->save();
        } else {
            $this->business_personnel_id = 0;
            $this->locker_id = 0;
            $this->refund_order_status = self::REFUND_STATUS_NEW;

            $userId = Auth::guard('api')->id();
            $userName = User::find($userId)->real_name;
            $operationData = new RefundOperationRecord;
            $operationData->refund_orders_id = $this->id;
            $operationData->user_id = Auth::guard('api')->id();
            $operationData->user_name = $userName;
            $operationData->operation = "解锁";
            $operationData->description = "订单解锁";
            $operationData->save();
        }

        $this->save();
    }

    /**
     * 客审
     *
     * @return bool
     */
    public function audit()
    {
        $this->locker_id = 0;
        $this->refund_order_status = self::REFUND_STATUS_CS_AUDIT;
        $this->cs_audit_at = Carbon::now();
        $this->save();

        $userId = Auth::guard('api')->id();
        $userName = User::find($userId)->real_name;
        $operationData = new RefundOperationRecord;
        $operationData->refund_orders_id = $this->id;
        $operationData->user_id = Auth::guard('api')->id();
        $operationData->user_name = $userName;
        $operationData->operation = "客审";
        $operationData->description = "客审";
        $operationData->save();
    }
    /**售后驳回*/
    public function asDoRefuse()
    {
        $this->locker_id = 0;
        $this->refund_order_status = self::REFUND_STATUS_NEW;
        $this->locked_at = null;
        $this->save();

        $userId = Auth::guard('api')->id();
        $userName = User::find($userId)->real_name;
        $operationData = new RefundOperationRecord;
        $operationData->refund_orders_id = $this->id;
        $operationData->user_id = Auth::guard('api')->id();
        $operationData->user_name = $userName;
        $operationData->operation = "售后驳回";
        $operationData->description = "售后驳回";
        $operationData->save();
    }

    /**
     * 退审
     *
     * @return bool
     */
    public function unAudit()
    {
        $this->business_personnel_id = 0;
        $this->refund_order_status = self::REFUND_STATUS_NEW;
        $this->cs_audit_at = null;
        $this->save();

        $userId = Auth::guard('api')->id();
        $userName = User::find($userId)->real_name;
        $operationData = new RefundOperationRecord;
        $operationData->refund_orders_id = $this->id;
        $operationData->user_id = Auth::guard('api')->id();
        $operationData->user_name = $userName;
        $operationData->operation = "客服退审";
        $operationData->description = "客服退审";
        $operationData->save();
    }

    /**
     * 售后未锁定.
     *
     * @return bool
     */
    public function asUnlock()
    {
        return !(($this->getOriginal('refund_order_status') == self::REFUND_STATUS_LOCK) || ($this->getOriginal('refund_order_status') == self::REFUND_STATUS_AS_LOCK) || ($this->getOriginal('refund_order_status') == self::REFUND_STATUS_FD_LOCK));
    }

    /**
     * 售后订单锁定或释放.
     *
     * @return bool
     */
    public function asLockOrUnlock()
    {
        if ($this->asUnlock()) {
            $this->locker_id = Auth::guard('api')->id();
            $this->refund_order_status = self::REFUND_STATUS_AS_LOCK;

            $userId = Auth::guard('api')->id();
            $userName = User::find($userId)->real_name;
            $operationData = new RefundOperationRecord;
            $operationData->refund_orders_id = $this->id;
            $operationData->user_id = Auth::guard('api')->id();
            $operationData->user_name = $userName;
            $operationData->operation = "售后锁定";
            $operationData->description = "售后锁定";
            $operationData->save();
        } else {
            $this->locker_id = 0;
            $this->refund_order_status = self::REFUND_STATUS_CS_AUDIT;

            $userId = Auth::guard('api')->id();
            $userName = User::find($userId)->real_name;
            $operationData = new RefundOperationRecord;
            $operationData->refund_orders_id = $this->id;
            $operationData->user_id = Auth::guard('api')->id();
            $operationData->user_name = $userName;
            $operationData->operation = "售后解锁";
            $operationData->description = "售后解锁";
            $operationData->save();
        }

        $this->save();
    }

    /**
     * 售后审核.
     *
     * @return bool
     */
    public function asAudit()
    {
        $this->locker_id = 0;
        $this->after_sales_id = Auth::guard('api')->id();
        $this->refund_order_status = self::REFUND_STATUS_AS_AUDIT;
        $this->as_audit_at = Carbon::now();
        $this->save();

        $userId = Auth::guard('api')->id();
        $userName = User::find($userId)->real_name;
        $operationData = new RefundOperationRecord;
        $operationData->refund_orders_id = $this->id;
        $operationData->user_id = Auth::guard('api')->id();
        $operationData->user_name = $userName;
        $operationData->operation = "售后审核";
        $operationData->description = "售后审核";
        $operationData->save();
    }

    /**
     * 售后退审
     *
     * @return bool
     */
    public function asUnAudit()
    {
        $this->after_sales_id = 0;
        $this->refund_order_status = self::REFUND_STATUS_CS_AUDIT;
        $this->as_audit_at = null;
        $this->save();

        $userId = Auth::guard('api')->id();
        $userName = User::find($userId)->real_name;
        $operationData = new RefundOperationRecord;
        $operationData->refund_orders_id = $this->id;
        $operationData->user_id = Auth::guard('api')->id();
        $operationData->user_name = $userName;
        $operationData->operation = "售后退审";
        $operationData->description = "售后退审";
        $operationData->save();
    }

    /**
     * 财务未锁定.
     *
     * @return bool
     */
    public function fdUnlock()
    {
        return !(($this->getOriginal('refund_order_status') == self::REFUND_STATUS_LOCK) || ($this->getOriginal('refund_order_status') == self::REFUND_STATUS_AS_LOCK) || ($this->getOriginal('refund_order_status') == self::REFUND_STATUS_FD_LOCK));
    }

    /**
     * 财务锁定或释放.
     *
     * @return bool
     */
    public function fdLockOrUnlock()
    {
        if ($this->fdUnlock()) {
            $this->locker_id = Auth::guard('api')->id();
            $this->refund_order_status = self::REFUND_STATUS_FD_LOCK;

            $userId = Auth::guard('api')->id();
            $userName = User::find($userId)->real_name;
            $operationData = new RefundOperationRecord;
            $operationData->refund_orders_id = $this->id;
            $operationData->user_id = Auth::guard('api')->id();
            $operationData->user_name = $userName;
            $operationData->operation = "财务锁定";
            $operationData->description = "财务锁定";
            $operationData->save();
        } else {
            $this->locker_id = 0;
            $this->refund_order_status = self::REFUND_STATUS_AS_AUDIT;

            $userId = Auth::guard('api')->id();
            $userName = User::find($userId)->real_name;
            $operationData = new RefundOperationRecord;
            $operationData->refund_orders_id = $this->id;
            $operationData->user_id = Auth::guard('api')->id();
            $operationData->user_name = $userName;
            $operationData->operation = "财务解锁";
            $operationData->description = "财务解锁";
            $operationData->save();
        }

        $this->save();
    }

    /**
     * 财务审核.
     *
     * @return bool
     */
    public function fdAudit()
    {
        $this->financial_id = 0;
        $this->after_sales_id = Auth::guard('api')->id();
        $this->refund_order_status = self::REFUND_STATUS_FD_AUDIT;
        $this->f_audit_at = Carbon::now();
        $this->save();

        $userId = Auth::guard('api')->id();
        $userName = User::find($userId)->real_name;
        $operationData = new RefundOperationRecord;
        $operationData->refund_orders_id = $this->id;
        $operationData->user_id = Auth::guard('api')->id();
        $operationData->user_name = $userName;
        $operationData->operation = "财务审核";
        $operationData->description = "财务审核";
        $operationData->save();
    }

    /**
     * 财务退审
     *
     * @return bool
     */
    public function fdUnAudit()
    {
        $this->financial_id = 0;
        $this->refund_order_status = self::REFUND_STATUS_AS_AUDIT;
        $this->f_audit_at = null;
        $this->save();

        $userId = Auth::guard('api')->id();
        $userName = User::find($userId)->real_name;
        $operationData = new RefundOperationRecord;
        $operationData->refund_orders_id = $this->id;
        $operationData->user_id = Auth::guard('api')->id();
        $operationData->user_name = $userName;
        $operationData->operation = "财务退审";
        $operationData->description = "财务退审";
        $operationData->save();
    }

    /**
     * 生成订单流水号.
     *
     * @param $prefix       订单流水号前缀
     * @param $index        字段名
     *
     * @return string
     */
    public static function findAvailableNo(String $prefix, String $index): String
    {
        do {
            // 随机生成订单号
            $no = $prefix.date('YmdHis').str_pad(mt_rand(1, 99999), 5, 0, STR_PAD_LEFT);
        } while (static::query()->where($index, $no)->exists());

        return $no;
    }

    public function getRefundOrderStatusAttribute($value)
    {
        return self::$refundStatusMap[$value] ?? $value;
    }

    public function paymentMethod()
    {
        return $this->belongsTo(PaymentMethod::class, 'payment_methods_id');
    }

    public function shop()
    {
        return $this->belongsTo(Shop::class, 'shops_id');
    }

    public function refundPaymentMethod()
    {
        return $this->belongsTo(PaymentMethod::class, 'refund_payment_methods_id');
    }

    public function refundReason()
    {
        return $this->hasMany(RefundReason::class);
    }

    public function refundReasonType()
    {
        return $this->belongsTo(RefundReasonType::class, 'refund_reason_type_id');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'creator_id');
    }

    public function businessPersonnel()
    {
        return $this->belongsTo(User::class, 'business_personnel_id');
    }

    public function locker()
    {
        return $this->belongsTo(User::class, 'locker_id');
    }

    public function afterSale()
    {
        return $this->belongsTo(User::class, 'after_sales_id');
    }

    public function financial()
    {
        return $this->belongsTo(User::class, 'financial_id');
    }

    public function refundOperationRecord()
    {
        return $this->hasMany(RefundOperationRecord::class, 'refund_orders_id');
    }
}
