<?php

namespace App\Models;

class Role extends Model
{
    protected $table = "roles";

    protected $fillable = [
        'id','name', 'description','remark','guard_name','status'
    ];

    protected $dates = [
       'created_at',
       'updated_at'
    ];

    protected $casts = [
        'status' => 'boolean'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // 监听模型创建事件，在写入数据库之前触发
        static::creating(function ($model) {
            // 如果模型的 order_status 字段为空
            if (!$model->guard_name) {
                $model->guard_name = "web";
                // 如果生成失败，则终止创建订单
                if (!$model->guard_name) {
                    return false;
                }
            }
        });
    }

    /**
     * 获取与角色关联的权限
     */
    public function permissions()
    {
        return $this->hasMany(Permission::class, 'permissions_id');
    }

    /**
     * 所在分组
     */
    public function roleGroup()
    {
        return $this->belongsTo(Rolegroup::class, 'role_group_id');
    }
}
